### ISSUE TITLE
Clarification on Exposing Credentials (API Key, URL, etc.) in environment.ts File

### ISSUE THREAD

**Issue by MitjaCH** [JeremyHefti/christlizzes#3]
Hello,

I noticed that sensitive credentials, including the API key and URL, are currently exposed publicly in the environment.ts file. Could you pleasea clarify if this is intentional, or if these credentials should be kept private for security reasons.

**Comment by nxkzty** [comment]
Hello Mitja, 

Thank you for your pointing that out to us we took care of it.

**Comment by MitjaCH** [comment]
ty <3

**Comment by MitjaCH** [comment]
![image](https://github.com/user-attachments/assets/c07549f1-04d5-48b6-9a45-c36869b8d050)

As shown in the image above, sensitive variables can still be exposed in your Angular code. This is because Angular's build process embeds all environment variables (such as API keys) into the final JavaScript files, which can be accessed by anyone who inspects the code.

For more information on how Angular handles environment variables, check out the [Angular build guide](https://v17.angular.io/guide/build).

### Secure Alternatives for Storing Sensitive Data

Instead of storing sensitive API keys directly in the `environment.ts` file, you can take a more secure approach:

1. **Use dotenv for Environment Variables**:  
   You can use the `dotenv` package in your backend or a secure Node.js server to store sensitive data like API keys. The `.env` file would not be exposed in the frontend and can be loaded into your application at runtime. Here's how you can do it:
   
   - Install dotenv:
     ```bash
     npm install dotenv
     ```

   - Create a `.env` file and store your sensitive data there:
     ```
     API_KEY=your-sensitive-api-key
     ```

   - In your application code, initialize dotenv to access these variables:
     ```javascript
     require('dotenv').config();
     
     const apiKey = process.env.API_KEY;
     ```

2. **Environment-specific Data**:  
   For non-sensitive configuration values that don't pose a security risk, you can continue using the `environment.ts` and `environment.prod.ts` files. Just ensure you don’t include any critical keys in these files, as they will still be bundled and exposed in the final JavaScript.

By separating sensitive data (e.g., API keys) into a secure backend and using environment variables, you can significantly reduce the risk of accidental exposure in your Angular app.

**Comment by nxkzty** [comment]
this is a outdated api key

**Comment by MitjaCH** [comment]
Ja aber nur will ihr jz environment.ts glöscht hend chame es jz nüm builde W aura. machs mit dotenv und anstatt döt 

`apiKey: "skibiditoilet"`

machsch

`apiKey: {process.env.API_KEY}`

**Comment by MitjaCH** [comment]
denn packsch api key in das repository und in secrets denn sind das wie env variables und me chas wieder builde ohni de api key kenne

**Comment by JeremyHefti** [comment]
Thank you for your suggestion! We have reviewed it and implemented it in the project. We appreciate your contribution!

WE LOVE YOU MITJA

**Comment by MitjaCH** [comment]
fwaeh
